# Generated by Django 6.0.3 on 2026-04-28 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_memberpreregistrationlink_memberpreregistration_and_more'),
        ('organizations', '0004_organization_contact_sensitiveactivitylog'),
        ('subscriptions', '0003_alter_subscriptionplan_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('awaiting_payment', 'Paiement en cours'), ('paid', 'Payee'), ('cancelled', 'Annulee'), ('failed', 'Echec')], db_index=True, default='pending', max_length=30)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aggregator_reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='organizations.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='members.member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_requests', to='subscriptions.subscriptionplan')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', 'member', 'status'], name='subscriptio_gym_id_94973f_idx'), models.Index(fields=['gym', 'created_at'], name='subscriptio_gym_id_028553_idx'), models.Index(fields=['status', 'created_at'], name='subscriptio_status_61d02f_idx')],
            },
        ),
    ]
