# Generated by Django 6.0.3 on 2026-05-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_remove_accountant_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergymrole',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('coach', 'Coach'), ('reception', 'Receptionist'), ('cashier', 'Cashier')], max_length=20),
        ),
    ]
